---
version: 2

scripts: &scripts
  steps:
    - checkout
    - run: yarn
    - run: yarn test
    - run: yarn lint
    - run: yarn build

jobs:
  node-10:
    <<: *scripts
    docker:
      - image: circleci/node:10
  node-12:
    <<: *scripts
    docker:
      - image: circleci/node:12
  node-13:
    <<: *scripts
    docker:
      - image: circleci/node:13
  node-14:
    <<: *scripts
    docker:
      - image: circleci/node:14

workflows:
  version: 2
  build:
    jobs:
      - node-10
      - node-12
      - node-13
      - node-14
