name: review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        node: [16.x]
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v2

      - name: ðŸ— Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn

      - name: ðŸ“¦ Install dependencies
        run: yarn install --frozen-lockfile --check-files

      - name: âœ… Lint code
        run: yarn lint

      - name: ðŸ§ª Test code
        run: yarn test

      - name: ðŸ‘· Build code
        run: yarn clean && yarn build

      - name: ðŸ•µï¸ Validate build
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol build/ | wc -l)" -gt "0" ]; then
            echo "âš ï¸ Build is outdated"
            echo "    > run 'yarn clean', 'yarn build', and commit changes"
            git diff
            exit 1
          fi
      
      - name: ðŸ—‚ Upload build
        uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: build
          path: build/
