name: review

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Setup repo
        uses: actions/checkout@v4

      - name: ðŸ— Setup runner
        uses: ./.github/actions/setup

      - name: ðŸ“¦ Install dependencies
        run: bun install

      - name: âœ… Lint code
        run: bun run lint --max-warnings=0

      - name: ðŸ§ª Test code
        run: bun run test

      - name: ðŸ‘· Build code
        run: bun run clean && bun run build

      - name: ðŸ•µï¸ Validate build
        id: diff
        run: |
          if [ "$(git diff --ignore-space-at-eol build/ | wc -l)" -gt "0" ]; then
            echo "âš ï¸ Build is outdated"
            echo "    > run 'bun run clean', 'bun run build', and commit changes"
            git diff
            exit 1
          fi

      - name: ðŸ—‚ Upload build
        uses: actions/upload-artifact@v4
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        with:
          name: build
          path: build/
